package com.ecommerce.event;

public enum EventType {
    ORDER_CREATED,
    PAYMENT_SUCCESS,
    PAYMENT_FAILED,
    INVENTORY_UPDATED,
    INVENTORY_RESERVED,
    INVENTORY_RELEASED,
    ORDER_CANCELLED,
    ORDER_RETURNED,
    CART_UPDATED,
    FRAUD_DETECTED,
    RESERVATION_EXPIRED
}
